name: Bot Stats Logger

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:

  bot1:
    name: Bot 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: "Build logger"
        run: |
          cd dstat
          docker build . -t dstat
          cd ..
          docker run -t -a stdout dstat -token $TOKEN -json > bot1.json
        env:
          TOKEN: ${{ secrets.BOT_1_TOKEN }}
      - name: "Commit and push"
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase
          git commit -am "Logged bot1.json" || true
          git push origin master || true

  bot2:
    name: Bot 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: "Build logger"
        run: |
          cd dstat
          docker build . -t dstat
          cd ..
          docker run -t -a stdout dstat -token $TOKEN -json > bot2.json
        env:
          TOKEN: ${{ secrets.BOT_2_TOKEN }}
      - name: "Commit and push"
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase
          git commit -am "Logged bot2.json" || true
          git push origin master || true